name: PyPI Release and Docker Build

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  release-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Specify your desired Python version

      - name: Install Poetry
        run: pip install poetry

      - name: Build package
        run: poetry build

      - name: Configure Poetry to use PyPI token
        run: poetry config pypi-token.pypi ${{ secrets.PYPYTOKEN }}

      - name: Publish to PyPI
        run: poetry publish

      # Docker build and push steps start here
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vectrix:latest