name: Release

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify your desired Python version

      - name: Install Poetry
        run: pip install poetry

      - name: Extract version from pyproject.toml
        id: extract_version
        run: |
          VERSION=$(poetry version -s)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | gh auth login --with-token

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: |
          if [ ! -z "$VERSION" ]; then
            gh release create $VERSION --notes "Release $VERSION"
          else
            echo "Version could not be determined."
            exit 1
          fi